restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls'))
]

restaurant/restaurant_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuList.as_view(), name='home'),
    path('item/<int:pk>/', views.MenuItemDetail.as_view(), name='menu_item'),
]

restaurant/restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User


MEAL_TYPE = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("desserts", "Desserts"),
)

STATUS =(
    (0, "Unavailable"),
    (1, "Available")
)
class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    meal_type = models.CharField(max_length=200, choices=MEAL_TYPE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUS, default=1)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.meal

restaurant/restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item,MEAL_TYPE

class MenuList(generic.ListView):
    queryset = Item.objects.order_by("-date_created")
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meals"] = MEAL_TYPE
        return context
class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = "menu_item_detail.html"

restaurant/restaurant_menu/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <title>Menu Products</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                    <a class="navbar-brand" href="#"></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                         <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

<!-- JavaScript Bundle with Popper -->
             <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    </body>
</html>

restaurant/restaurant_menu/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1> Restaurant Menu </h1>
        <ul class="list-group list-group-flush">
            {% for meal in meals %}
                <h2 class="pt-5"> {{meal.1}}</h2>
                    {% for row in item_list %}
                        {% if row.meal_type == meal.0 %}
                            {% if row.status == 0 %}
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 pd-0">
                                <a href="{% url 'menu_item' row.pk %}"><h3><del>{{ row.meal }}</del></h3></a>
                                <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                            </li>
                            <li class="list-group-item pt-0">
                                <p>{{row.description }}</p>
                            </li>
                            {% else %}
                           <li class="list-group-item d-flex justify-content-between align-items-center border-0 pd-0">
                                <a href="{% url 'menu_item'  row.pk %}"><h3>{{ row.meal }}</h3></a>
                                <span class="badge bg-primary rounded-pill">{{ row.price }}</span>
                           </li>
                           <li class="list-group-item pt-0">
                                <p>{{row.description }}</p>
                           </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
            {% endfor %}
        </ul>
</div>
{% endblock content %}

restaurant/restaurant_menu/templates/menu_item_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1 class="pt-5">{{ item.meal }}</h1>
  <p> {{ item.description }}  </p>
  <p> {{ item.price }}  </p>
</div>
{% endblock content %}